export const testConfig = {
  empty_credentials: "Please provide USERNAME and PASSWORD",
  empty_url: "Please provide the BASE_URL",
  limitedCompany: "Limited Company",
  limitedPartnership: "Limited partnership",
  limitedLiabilityPartnership: "Limited liability partnership",
  partnership: "Partnership",
  soleTrader: "Sole trader",
  otherType: "Other",
  unincorporatedEntity: "Unincorporated Entity",
  corporateBody: "Corporate Body",
  notRelevantRole: "Someone Else",
  director: "DIRECTOR",
  nameOfBusinessRadio: "Name of the business",
  yourNameRadio: "Your name",
  bothRadio: "Both",
  generalPartner: "General Partner",
  member: "Member",
  memberGoverningBody: "Member of governing body",
  auditors:
    "Auditors, insolvency practitioners, external accountants and tax advisers",
  legalProfessionals: "Independent legal professionals",
  companyServiceProviders: "Trust or company service providers",
  creditInstitutions: "Credit institutions",
  other: "Other",
  estateAgents: "Estate agents",
  highValueDealers: "High value dealers",
  casinos: "Casinos",
  fees: "£100.00",
  cardNumber: "4444333322221111",
  expiryMonth: "12",
  expiryYear: "2027",
  nameOnCard: "TestCardName",
  cvc: "123",
  addressLine1: "testaddress",
  city: "testcity",
  postcode: "ST63JL",
  companyName: "LLOYDS BANK PLC",
};
