export const testConfig = {
  baseUrl: process.env.BASE_URL,
  userName: process.env.USERNAME,
  password: process.env.PASSWORD,
  empty_credentials: "Please provide USERNAME and PASSWORD",
  empty_url: "Please provide the BASE_URL",
  limitedCompany: "Limited Company",
  limitedPartnership: "Limited partnership",
  limitedLiabilityPartnership: "Limited liability partnership",
  partnership: "Partnership",
  soleTrader: "Sole trader",
  otherType: "Other",
  notRelevantRole: "Someone Else",
  director: "DIRECTOR",
  nameOfBusinessRadio: "Name of the business",
  yourNameRadio: "Your name",
  bothRadio: "Both",
  generalPartner: "General Partner",
  member: "Member",
};
